apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
  - name: server
    image: cpp_server:1.11
    ports:
    - containerPort: 8085
    volumeMounts:
      - mountPath: "/opt/certificates"
        name: ssh-key
        readOnly: true
  volumes:
    - name: ssh-key
      secret:
        secretName: test-tls
