apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-server
  labels:
    app: cpp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpp-server
  template:
    metadata:
      labels:
        app: cpp-server
    spec:
      containers:
      - name: cpp-server
        image: ngbe:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret1
          mountPath: /opt/certificates
      volumes:
      - name: secret1
        secret:
          secretName: server-tls
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-03-31T21:45:41Z"
  labels:
    app: cppservice
  name: cppservice
spec:
  type: NodePort
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: 8443
  selector:
    app: cpp-server
---
apiVersion: v1
kind: Secret
metadata:
  name: server-tls
data:
  tls.key: "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUlWdjY4VHhxelJhc01YWElaQmphNEtyNGg4c1V3dmRqUFJRdXZWQklDM1hvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFL3pNQnpVMVJldnJrTWxpOVFrUnY0U2duOEZlclJUTEdpa3ptMFIvUVZkVFdaNE80VUJ3Ywo1YmtkVGVDWTZ5OWEwUCttME5VTWtGbG5EMWR4OVBNeEtRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJIakNCeGdJVVE4MnBnZWJ3R0ZVNFc1Slp3R2ZDTG1ob1J6QXdDZ1lJS29aSXpqMEVBd0l3RVRFUE1BMEcKQTFVRUF3d0dVbTl2ZEVOQk1CNFhEVEkwTURRd05ESXlNamN4TkZvWERUSTJNVEl6TURJeU1qY3hORm93RkRFUwpNQkFHQTFVRUF3d0piRzlqWVd4b2IzTjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUUvek1CCnpVMVJldnJrTWxpOVFrUnY0U2duOEZlclJUTEdpa3ptMFIvUVZkVFdaNE80VUJ3YzVia2RUZUNZNnk5YTBQK20KME5VTWtGbG5EMWR4OVBNeEtUQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQUM2UmpZQWtZZmRaaHlYMU5IUU4yNgo0c1pMakNoNWVEdTlSM0t6SU9aTW93SWdVUDVEelhMQUtXbnhTVzNBTCtxYVJMVmRiQzFnRmlNSU9aMDVoR0lvCkxnQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  ca.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJHekNCd3dJVUx4S2ZyOUdMS0JOR1p6Y204UVc1Y2tyN2pkd3dDZ1lJS29aSXpqMEVBd0l3RVRFUE1BMEcKQTFVRUF3d0dVbTl2ZEVOQk1CNFhEVEkwTURRd01URTROVEUwT0ZvWERUSTBNRFV3TVRFNE5URTBPRm93RVRFUApNQTBHQTFVRUF3d0dVbTl2ZEVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUZRU0c0TVBjCmt2TjBtMjY1QzdCY254MDdiQ0VEM3RkeGtwYXJaYnA4YmFsaVVKMkpWNHdYcWMzTTgyR1dmYWdMTG40NlBXVnkKOGVnY0haTStlVmhIMnpBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCc0IvaEFlVWhlSC9HcDdDeU5JcGwyRmJqVQpWUVZGQXFMQWt6UERwcUxBWndJZ09WWjBzUEVuWFl5cnM4YWp5ZC8rZURWSUphaEI0S2UwRUY3djRhR1NBa1k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
